cdh:
  image: chalimartines/cdh5-pseudo-distributed
  hostname: cdh
  ports:
    - "8020:8020"
    - "50070:50070"
    - "50010:50010"
    - "50020:50020"
    - "50075:50075"
    - "8030:8030"
    - "8031:8031"
    - "8032:8032"
    - "8033:8033"
    - "8088:8088"
    - "8040:8040"
    - "8042:8042"
    - "10020:10020"
    - "19888:19888"

zookeeper:
  image: jplock/zookeeper
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"

mastermesos:
  image: redjack/mesos-master
  ports:
    - "5050:5050"
  links:
    - zookeeper:zookeeper
  environment:
    - MESOS_LOG_DIR=/var/log
    - MESOS_HOSTNAME=localhost
    - MESOS_WORK_DIR=/tmp
    - MESOS_QUORUM=1
    - MESOS_ZK=zk://zookeeper:2181/mesos


slavemesos:
  image: chalimartines/mesos-slave
  ports:
    - "5051:5051"
  links:
    - zookeeper:zookeeper
    - cdh:cdh
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /sys:/sys
    - /proc:/proc
  environment:
    - MESOS_LOG_DIR=/var/log
    - MESOS_HOSTNAME=localhost
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_ISOLATION=cgroups/cpu,cgroups/mem
    - MESOS_CONTAINERIZERS=docker,mesos

chronos:
  image: banno/chronos
  command: --master zk://zookeeper:2181/mesos --zk_hosts zookeeper:2181 --http_port 8081
  ports:
    - "8081:8081"
  links:
    - zookeeper:zookeeper
